//
// Created by Giulio Carota on 17/10/21.
//

#ifndef SCREENRECLIB_SCPPVIDEOTRANSCODER_H
#define SCREENRECLIB_SCPPVIDEOTRANSCODER_H


class SCPPVideoTranscoder {

};


#endif //SCREENRECLIB_SCPPVIDEOTRANSCODER_H
